title: "[Idea]: "
labels: ["enhancement", "idea"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea! This plugin provides Chart.js expertise through Claude Code.

        Ideas can be about **plugin mechanics** (how skills trigger, command behavior) or **Chart.js coverage** (topics, techniques, frameworks to add).

        **Before submitting**: Check [existing ideas](../../discussions/categories/ideas).

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I've searched existing ideas and discussions
          required: true

  - type: dropdown
    id: idea-type
    attributes:
      label: Idea Type
      description: "Is this about the plugin itself or the Chart.js content it provides?"
      options:
        - Chart.js coverage (new topics, techniques, examples)
        - Plugin mechanics (skills, commands, agent behavior)
        - Both / Not sure
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: "Select the area this idea relates to"
      options:
        - Chart types coverage
        - Framework integrations (React, Vue, Angular, Rails)
        - Configuration and options
        - Axes and scales
        - Animations and transitions
        - Plugin development guidance
        - /chartjs:component command
        - Skill triggering or content
        - Agent behavior
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Need
      description: "What problem does this idea solve?"
      placeholder: |
        Example (coverage): "The plugin doesn't cover time-series axes well..."
        Example (mechanics): "The agent doesn't trigger when I'm working on..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Idea
      description: "Describe your idea clearly"
    validations:
      required: true

  - type: textarea
    id: benefit
    attributes:
      label: Expected Benefit
      description: "How would this improve the plugin?"
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution interest
      options:
        - label: I'd be willing to help implement this idea
          required: false
