title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? This could be about:
        - **Using the plugin** with Claude Code
        - **Chart.js topics** the plugin should help with
        - **Contributing** to the plugin

        **Resources**: [README](../../blob/main/README.md) | [Chart.js Docs](https://www.chartjs.org/docs/latest/)

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I've checked the README
          required: true
        - label: I've searched existing discussions
          required: true

  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      description: "What's your question about?"
      options:
        - Using the plugin with Claude Code
        - Chart.js topic the plugin covers
        - Chart.js topic the plugin should cover
        - Contributing to the plugin
        - Other
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: "Select the most relevant area"
      options:
        - Plugin installation / setup
        - Skill triggering
        - /chartjs:component command
        - Agent behavior
        - Chart types
        - Framework integrations
        - Configuration / options
        - Axes and scales
        - Animations
        - Tooltips and legends
        - Custom plugins
        - Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: "What would you like to know?"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: "Any relevant details, code snippets, or screenshots"
    validations:
      required: false

  - type: input
    id: claude-code-version
    attributes:
      label: Claude Code Version (for plugin issues)
      description: "Run `claude --version` if this is about plugin behavior"
      placeholder: "e.g., 1.0.37"
    validations:
      required: false

  - type: input
    id: chartjs-version
    attributes:
      label: Chart.js Version (for coverage questions)
      description: "This plugin targets v4.5.1"
      placeholder: "e.g., 4.5.1"
    validations:
      required: false
