title: "[Show & Tell]: "
labels: ["showcase"]
body:
  - type: markdown
    attributes:
      value: |
        Share what you've accomplished! This could be:
        - **Charts you built** with help from this plugin
        - **Contributions** you made to the plugin
        - **Learnings** from using Chart.js or this plugin

        **Tip**: Screenshots and code snippets help others learn from your work.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: My showcase doesn't expose sensitive information
          required: true

  - type: dropdown
    id: showcase-type
    attributes:
      label: What are you showcasing?
      description: "Select the type of showcase"
      options:
        - Chart.js visualization I built
        - Dashboard or multi-chart project
        - Plugin contribution (skill, command, etc.)
        - Learning or technique discovery
        - Other
    validations:
      required: true

  - type: dropdown
    id: framework
    attributes:
      label: Framework (if applicable)
      description: "What did you build with?"
      options:
        - Not applicable
        - Vanilla JavaScript
        - React
        - Vue
        - Angular
        - Rails / Stimulus
        - Next.js
        - Other
    validations:
      required: false

  - type: textarea
    id: showcase
    attributes:
      label: What You're Sharing
      description: "Describe what you built or learned"
    validations:
      required: true

  - type: textarea
    id: learnings
    attributes:
      label: Key Learnings
      description: "What insights might help others?"
      placeholder: |
        The plugin helped me realize...
        A tip for others: ...
    validations:
      required: true

  - type: textarea
    id: links
    attributes:
      label: Links or Resources
      description: "Repository, demo, or relevant links"
    validations:
      required: false

  - type: checkboxes
    id: consent
    attributes:
      label: Sharing preferences
      options:
        - label: This can be featured in project documentation
          required: false
        - label: Code snippets can be shared as examples
          required: false
