name: Bug Report
description: Report a bug or issue with the chartjs-expert plugin
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide details to help us diagnose and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Tell us what happened
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Load plugin with `claude /install-plugin ...`
        2. Ask about Chart.js configuration
        3. Run `/chartjs:component`
        4. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
    validations:
      required: true

  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Type
      description: Is this a plugin mechanics issue or incorrect Chart.js guidance?
      options:
        - Plugin mechanics (skill not triggering, command error, etc.)
        - Incorrect Chart.js guidance (wrong code, outdated API, etc.)
        - Both / Not sure
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which part of the plugin is affected?
      options:
        - /chartjs:component command
        - Skill - chartjs-overview
        - Skill - chartjs-chart-types
        - Skill - chartjs-configuration
        - Skill - chartjs-axes
        - Skill - chartjs-plugins
        - Skill - chartjs-developers
        - Skill - chartjs-integrations
        - Skill - chartjs-animations
        - Skill - chartjs-tooltips
        - Skill - chartjs-advanced
        - Agent - chartjs-expert
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: framework
    attributes:
      label: Framework (if applicable)
      description: Were you using Chart.js with a specific framework?
      options:
        - Not applicable
        - Vanilla JavaScript
        - React (react-chartjs-2)
        - Vue (vue-chartjs)
        - Angular (ng2-charts)
        - Rails / Stimulus
        - Next.js
        - Other
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      placeholder: |
        - OS: macOS 15.0
        - Claude Code Version: 1.0.37
        - Chart.js Version: 4.5.1
      render: yaml
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Error Messages
      description: Any relevant logs or error messages
      render: shell

  - type: textarea
    id: code
    attributes:
      label: Relevant Code (if applicable)
      description: Chart.js configuration or code that triggered the issue
      render: javascript

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Screenshots, links to Chart.js docs, or other relevant information
