name: Documentation Improvement
description: Suggest improvements to documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Clear docs help everyone use the plugin effectively.

  - type: dropdown
    id: doc-type
    attributes:
      label: Which documentation needs improvement?
      options:
        - README.md
        - CLAUDE.md
        - CONTRIBUTING.md
        - CHANGELOG.md
        - Skill - chartjs-overview
        - Skill - chartjs-chart-types
        - Skill - chartjs-configuration
        - Skill - chartjs-axes
        - Skill - chartjs-plugins
        - Skill - chartjs-developers
        - Skill - chartjs-integrations
        - Skill - chartjs-animations
        - Skill - chartjs-tooltips
        - Skill - chartjs-advanced
        - Command - /chartjs:component
        - Agent - chartjs-expert
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Specific Location
      description: File path or section name
      placeholder: "e.g., README.md - Installation section"

  - type: textarea
    id: issue
    attributes:
      label: What's unclear or missing?
      description: Describe what's confusing, incorrect, or missing
      placeholder: The documentation doesn't explain...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you improve it? (Feel free to include proposed wording)

  - type: checkboxes
    id: issue-type
    attributes:
      label: Type of issue
      options:
        - label: Incorrect information
        - label: Missing information
        - label: Unclear explanation
        - label: Code example needed
        - label: Outdated Chart.js API usage
        - label: Broken link
        - label: Typo or grammar
        - label: Other

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Screenshots, links to Chart.js docs, or other relevant information
