name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! This could be about plugin mechanics or Chart.js coverage.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: Is this about plugin mechanics or Chart.js content?
      options:
        - Chart.js coverage (new topics, techniques, examples)
        - Plugin mechanics (command, skill, agent behavior)
        - Both / Not sure
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Need
      description: What problem does this feature solve?
      placeholder: |
        Example (coverage): "The plugin doesn't help with Chart.js streaming data..."
        Example (mechanics): "The /chartjs:component command doesn't support..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe what you'd like
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Which component would this affect?
      options:
        - /chartjs:component command
        - Existing skill (specify below)
        - New skill request
        - Agent - chartjs-expert
        - New chart type coverage
        - New framework integration
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: component-name
    attributes:
      label: Specific Component (if applicable)
      description: Which skill, chart type, or framework?
      placeholder: "e.g., chartjs-axes skill, bubble charts, Svelte integration"

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other solutions you've thought about

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Would significantly improve my workflow
        - Medium - Would be nice to have
        - Low - Just a suggestion
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to help implement this feature
