name: Question or Support
description: Ask a question about using the chartjs-expert plugin
title: "[Question]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!

        **Consider [GitHub Discussions](https://github.com/sjnims/chartjs-expert/discussions) instead** - questions often get faster community responses there.

        **Resources**: [README](../../blob/main/README.md) | [Chart.js Docs](https://www.chartjs.org/docs/latest/)

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I've checked the README
          required: true
        - label: I've searched existing issues and discussions
          required: true
        - label: I've considered posting in GitHub Discussions instead
          required: true

  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      description: What's your question about?
      options:
        - Using the plugin with Claude Code
        - Chart.js topic the plugin covers
        - Chart.js topic the plugin should cover
        - Contributing to the plugin
        - Other
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Select the most relevant area
      options:
        - Plugin installation / setup
        - /chartjs:component command
        - Skill triggering
        - Agent behavior
        - Chart types
        - Framework integrations
        - Configuration / options
        - Axes and scales
        - Animations
        - Tooltips and legends
        - Custom Chart.js plugins
        - Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...? Why does...? Can I...?
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: What have you tried?
      description: Steps you've already taken
      placeholder: "I've tried... I looked at..."

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Code snippets, screenshots, or other relevant information

  - type: input
    id: chartjs-version
    attributes:
      label: Chart.js Version (if relevant)
      description: This plugin targets v4.5.1
      placeholder: "e.g., 4.5.1"
